names = input('Введите три любых имени, разделенных пробелом: ')
names_list = names.split(' ')
print(f'Первое имя: {names_list[0]}')
print(f'Второе имя: {names_list[1]}')
print(f'Третье имя: {names_list[2]}')